config/routes.rb
Rails.application.routes.draw do
  root :to => "static_pages#index"

  resources :posts

  match 'tagged' => 'posts#tagged', :as => 'tagged', :via => [:get]
  match '/api/posts/publish' => 'posts#publish', :via => [:post]
  match '/api/tags' => 'tags#allthetags', :via => [:get]
  match '/api/tags/search/:name' => 'tags#tagsearch', :via => [:get]
  match '/api/tags/search/' => 'tags#allthetags', :via => [:get]
  match 'taggedbyid' => 'posts#tagged', :as => 'taggedbyid', :via => [:get]


end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new

    if(params[:wiki].present?)
      @post.title = params[:wiki]
      mechanize = Mechanize.new
      destination = 'http://wiki.cheggnet.com/' + params[:wiki]
      wikipage = mechanize.get(destination)
      @post.title = wikipage.title
      @post.body = wikipage.search(".content")
    end

    render :new

  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :show
  end

  def update
    @post = Post.find(params[:id])
    if (params[:tag_list])
      @post.tag_list = params[:tag_list]
    end
    p params
    if @post.update_attributes(post_params)
      render :show
    else
      render :json => "ruh roh"
    end
  end

  def destroy
    #TODO
  end

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
    render :index
  end

  # create a post from the provided title, body, tags.
  # returns the post in json format
  def publish
    @post = Post.new
    @post.title = params.require(:title)
    @post.body = params.require(:body)
    @post.tag_list = params.require(:tags)
    @post.save
    render :json => @post
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id, :tag_list)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used(10)
    render :index
  end
  
  def tagged
    if params[:tag].present? 
      @posts = Post.tagged_with(params[:tag])
    else 
      @posts = Post.all
    end  
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # get all the tags
  # (allthethings)
  def allthetags
    @tagArray = []
    ActsAsTaggableOn::Tag.all.each do |tag|
      @tagArray.push({text: tag.name, id:tag.id, count:tag.taggings_count})
    end
    render :json => @tagArray
  end

  # get tags which contain a provided search string
  # the search string should be provided as the :name params
  #
  # returns a json array with all tags which contain the :name
  # as part of their tag names
  def tagsearch
    @name = params[:name].downcase
    @tagArray = []
    ActsAsTaggableOn::Tag.all.each do |tag|
      if tag.name.downcase.index(@name) != nil
        @tagArray.push({text: tag.name, id:tag.id, count:tag.taggings_count})
      end
    end
    render :json => @tagArray
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chegg Delta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">

<!-- Chegg menu logo -->
<!-- Nav right menu icon -->
<div id="nav-links"><a href="/"><%= image_tag "chegg_menu_logo.png", {class: 'chegg-menu-logo'} %></a><a class="fa-bar-link" href="#"><i class="fa fa-bars"></i></a><a href="/posts/new"><i class="fa fa-plus-circle"></i></a></div>

<!-- Tag overlay -->
<div id="tag-overlay">
  <a class="fa-times-link"><i class="fa fa-times"></i></a>
  <div class="row">
    <div class="small-11 small-centered columns first center">
      <span class="navigate-header"><a href="/" style="color:white">NAVIGATE BY TAG</a></span>
    </div>
  </div>
  <div class="row">
    <div class="small-12 small-centered columns tags-overlay-wrapper">
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<!-- <div class="row collapse all-post search-group">
  <div class="small-10 columns">
    <input type="text" placeholder="Search" id="search-box"></input>
  </div>
  <div class="small-2 columns">
    <a href="#" id="home-search-button" class="button postfix search-submit"><i class="fa fa-search"></i></a>
  </div>
</div> -->

<div class="row">
  <div class="small-12 columns first all-post-header">
  	<h1>Articles</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
  	<% @posts.each do |post| %>
    <div class="all-post-link">
  	  <a href="<%=post_url(post.id) %>"> <%= post.title %> </a>
    </div>
      <div class="all-post-body">
        <%= strip_tags(post.body)[0,100] %>...
      </div>
      <div class="all-post-section all-post-tags">
        <i class="fa fa-tags"></i><span class="post-tag-header">TAGS:</span>
        <% post.tags.each do |tag| %>
          <%= link_to tag.name, tagged_url(:tag => tag.name), :class=>"featured-tag" %>
        <% end %>
      </div>
      <div class="all-post-section all-post-modified">
        <i class="fa fa-clock-o"></i><span class="post-tag-header">UPDATED:</span>
        <% @time = (Time.now.getutc - post.updated_at).to_i %>
        <% case @time %>
        <% when 0...45 %>
        <%= "A few seconds ago" %>
        <% when 45...90 %>
        <%= "About a minute ago" %>
        <% when 90...3600 %>
        <%= (@time / 60).to_s + " minutes ago" %>
        <% when 3601...(3600*2-1) %>
        <%= "Over an hour ago" %>
        <% when 3600*2...(3600*24-1) %>
        <%= (@time/3600).to_s + " hours ago" %>
        <% when 3600*24...(3600*24*2-1) %>
        <%= "Over a day ago" %>
        <% when 3600*24*2...(3600*24*365-1) %>
        <%= (@time/(3600*24)).to_s + " days ago" %>
        <% when 3600*24*365...3600*24*365*2 %>
        <%= "Over a year ago" %>
        <% else %>
        <%= "Over" + (@time/(3600*24*365)).to_s + " years ago" %>
        <% end %>
      </div>
  	  <br />
  	<% end %>
  </div>
</div>

<!-- Static Pagination @TODO -->
<!-- <div class="row">
  <div class="small-8 small-centered columns center last pagination-wrapper">
    Page <span class="page-selected">1</span>
    <span class="page">2</span>
    <span class="page">3</span>
    <span class="page-ellipsis">...</span>
    <span class="page">9</span>
  </div>
</div> -->

app/views/posts/new.html.erb
<%= form_for @post, url: {action: "create"}, html: {class: "create-form"} do |f| %>
  <div class="row">
    <div class="large-12 columns first new-post-header">
        <%= f.text_field :title, {class: "new-post-title", placeholder: "Title", autofocus: true}  %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns new-post-body">
      <div id="post_body_editor">&nbsp;</div>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="large-12 columns new-post-tags">
      <span>
        <i class="fa fa-tags"></i>
        <%= f.text_field :tag_list, {class: "new-tags", placeholder: "Enter tags here"} %>
      </span>
    </div>
  </div>

<!--Attachments? -->
  <!-- <div class="row">
    <div class="large-12 columns attachments-wrapper">
      <span>
        <i class="fa fa-paperclip"></i>
        <div class="add-attachments">Any attachments?</div>
      </span>
    </div>
  </div> -->

  <div class = "row">
    <div class="large-2 columns">&nbsp;</div>
    <div class="large-8 columns">
      <%= f.submit "Publish", {class: "new-post-btn full-page-btn"} %>
    </div>
    <div class="large-2 columns">&nbsp;</div>
  </div>

  <%= f.text_area :body, style: ["display: none"] %>

<% end %>

app/views/posts/show.html.erb
<div class="row" id="wiki-title">
  	<input id ="wiki-title-input" type="text" value="<%= @post.title %>" disabled/>
</div>

<p />

<div class="row" id="wiki-content">
  <%=@post.body != nil ? @post.body.html_safe : "<br>".html_safe %>
</div>

<p />

<div class="row" id="wiki-tags">
  <i class="fa fa-tags"></i><span class="post-tag-header">TAGS:</span>
  <!-- <input type="text" id = "wiki-tags-input" value="<%= @post.tag_list %>"/> -->
  <% @post.tags.each do |tag| %>
    <%= link_to tag.name, tagged_url(:tag => tag.name), :class=>"featured-tag" %>
  <% end %>


</div>

<div class="row">
  <div class="small-12 columns last edit-wrapper" id="wiki-save" style="display:none">
      <span class="edit-header">You're editing!</span><br />
      <a onclick="Page.performPageAction('save', JSON.parse('<%=escape_javascript(@post.to_json) %>'))">Save</a> | <a onclick="Page.performPageAction('undo')">Undo</a>
  </div>
</div>

app/views/static_pages/index.html.erb
<!-- Title -->
<div class="row">
  <div class="small-8 small-centered columns center first">
    <%= image_tag "chegg_logo.png" %>
  </div>
</div>
<div class="row">
  <div class="small-8 small-centered columns center">
    <h1 id="headline">CHEGG DELTA</h1>
  </div>
</div>

<!-- Search Bar -->
 <div class="row collapse search-group">
  <div class="small-10 columns">
    <input type="text" placeholder="Search" id="search-box"></input>
  </div>
  <div class="small-2 columns">
    <a href="#" id="home-search-button" class="button postfix search-submit"><i class="fa fa-search"></i></a>
  </div>
</div>

<!-- New Post -->
<div class="row">
  <div class="small-8 small-centered columns">
    <div id="write-post">Start a new article...</div>
  </div>
</div>

<!-- New Post's Tags -->
<div class="row">
  <div class="small-8 small-centered columns">
    <span class="new-tag-wrapper opaque">
      <i class="fa fa-tags"></i><input type="text" class="new-tags" placeholder="Enter tags here">
    </span>
  </div>
</div>

<!-- Create New Post -->
<div class="row new-btn-wrapper opaque">
  <div class="small-8 small-centered columns">
    <div class="row">
      <div class="small-2 small columns">
        <a class="new-post-btn" onclick="Page.publish()">Publish</a>
      </div>
      <div class="small-10 small columns">
        <a class="new-post-btn" onclick="Page.fullscreen()">Go full screen</a>
      </div>
    </div>
  </div>
</div>

<!-- Featured tags -->
<div class="row">
  <div class="small-8 small-centered columns center">
    <section class="featured-tags">
      <strong><header class="popular-header">MOST POPULAR TAGS</header></strong>
      <br />
      <% @tags.each do |tag| %>
        <%= link_to tag.name, tagged_url(:tag => tag.name), :class=>"featured-tag" %>
      <% end %>
    </section>
  </div>
</div>

<style>
.chegg-menu-logo {
  display: none;
}
</style>